FROM centos:centos7

RUN yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# ENV
ENV JAVA_HOME=/etc/alternatives/java_sdk_1.8.0_openjdk
ENV JRE_HOME=$JAVA_HOME/jre
ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib:$CLASSPATH
ENV PATH=/sbin:$JAVA_HOME/bin:$PATH

# Define default command.
CMD ["bash"]
